//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamRider.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NamRider.API.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction is cancelled.
        /// </summary>
        internal static string CancelTransaction {
            get {
                return ResourceManager.GetString("CancelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already had critism this driving info.
        /// </summary>
        internal static string ExistingDrivingCritism {
            get {
                return ResourceManager.GetString("ExistingDrivingCritism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already had evaluate this driving info.
        /// </summary>
        internal static string ExistingDrivingEval {
            get {
                return ResourceManager.GetString("ExistingDrivingEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already had critism this park info.
        /// </summary>
        internal static string ExistingParkCritism {
            get {
                return ResourceManager.GetString("ExistingParkCritism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There existing a park with the same latitude longitude.
        /// </summary>
        internal static string ExistingParking {
            get {
                return ResourceManager.GetString("ExistingParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with the same login existing.
        /// </summary>
        internal static string ExistingUserLogin {
            get {
                return ResourceManager.GetString("ExistingUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is invalid.
        /// </summary>
        internal static string InvalidDescription {
            get {
                return ResourceManager.GetString("InvalidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driving info id is invalid.
        /// </summary>
        internal static string InvalidIdDriving {
            get {
                return ResourceManager.GetString("InvalidIdDriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parking info id is invalid.
        /// </summary>
        internal static string InvalidIdPark {
            get {
                return ResourceManager.GetString("InvalidIdPark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input data model is invalid.
        /// </summary>
        internal static string InvalidInputModel {
            get {
                return ResourceManager.GetString("InvalidInputModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latitude is invalid.
        /// </summary>
        internal static string InvalidLatitude {
            get {
                return ResourceManager.GetString("InvalidLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login is invalid.
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The longitude is invalid.
        /// </summary>
        internal static string InvalidLongitude {
            get {
                return ResourceManager.GetString("InvalidLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of place is invalid.
        /// </summary>
        internal static string InvalidNumberPlace {
            get {
                return ResourceManager.GetString("InvalidNumberPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rayon is invalid.
        /// </summary>
        internal static string InvalidRayon {
            get {
                return ResourceManager.GetString("InvalidRayon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street name is invalid.
        /// </summary>
        internal static string InvalidStreetName {
            get {
                return ResourceManager.GetString("InvalidStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type is invalid.
        /// </summary>
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of critism is invalid.
        /// </summary>
        internal static string InvalidValueCritism {
            get {
                return ResourceManager.GetString("InvalidValueCritism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of evaluation is invalid.
        /// </summary>
        internal static string InvalidValueEval {
            get {
                return ResourceManager.GetString("InvalidValueEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        internal static string InvaliPassword {
            get {
                return ResourceManager.GetString("InvaliPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A a error occured during operation.
        /// </summary>
        internal static string OccuredError {
            get {
                return ResourceManager.GetString("OccuredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required.
        /// </summary>
        internal static string Requiredässword {
            get {
                return ResourceManager.GetString("Requiredässword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is required .
        /// </summary>
        internal static string RequiredDescription {
            get {
                return ResourceManager.GetString("RequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is required.
        /// </summary>
        internal static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driving info id is required.
        /// </summary>
        internal static string RequiredIdDriving {
            get {
                return ResourceManager.GetString("RequiredIdDriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latitude is required.
        /// </summary>
        internal static string RequiredLatitude {
            get {
                return ResourceManager.GetString("RequiredLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The longitude is required.
        /// </summary>
        internal static string RequiredLongitude {
            get {
                return ResourceManager.GetString("RequiredLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rayon is required.
        /// </summary>
        internal static string RequiredRayon {
            get {
                return ResourceManager.GetString("RequiredRayon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street name is required.
        /// </summary>
        internal static string RequiredStreetName {
            get {
                return ResourceManager.GetString("RequiredStreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type is required.
        /// </summary>
        internal static string RequiredType {
            get {
                return ResourceManager.GetString("RequiredType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of critism is required.
        /// </summary>
        internal static string RequiredValueCritism {
            get {
                return ResourceManager.GetString("RequiredValueCritism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of critism is required.
        /// </summary>
        internal static string RequiredValueEval {
            get {
                return ResourceManager.GetString("RequiredValueEval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was succesfully.
        /// </summary>
        internal static string ValidOperation {
            get {
                return ResourceManager.GetString("ValidOperation", resourceCulture);
            }
        }

        public static string NoExistingDrivingEval { get; internal set; }
    }
}
